10. Личный проект: доверяй, но проверяй (часть 1)
htmlacademy-javascript/582985-keksobooking-21 pull request #4
Opened 2020-10-04 23:55 UTC by khisma17

1. Добавляет функционал активации страницы
2. Добавляет валидацию поля количества гостей

2020-10-05 17:21 UTC, frontstall requested changes
Адрес нельзя менять никак, кроме как передвижением метки. Сейчас поле адреса доступно для изменения вводом.

2020-10-05 17:21 UTC, frontstall commented on index.html
> +          <input id="address" name="address" type="text" value="603, 408">
Значение должно вычисляться в момент инициализации. Ещё важный момент: в неактивном состоянии указываются координаты центра метки, а в активном - острого конца метки. То есть координата Y будет одинакова. У тебя сейчас не так.

2020-10-05 17:21 UTC, frontstall commented on js/main.js
> +const MAIN_PIN_INACTIVE_X = 570 + 65 / 2;
Магические числа. Кроме того, это значение должно вычисляться, насколько я помню. Для этого надо взять ширину и высоту карты из DOM.

2020-10-05 17:21 UTC, frontstall commented on js/main.js
> +  if (evt.button === 0) {
Магическое число

2020-10-05 17:21 UTC, frontstall commented on js/main.js
> +const setAddress = () => {
Может, передавать координаты аргументами функции? Тогда можно будет использовать эту функцию в дальнейшем для установки разных координат.

2020-10-06 22:31 UTC, khisma17 commented on index.html
> +          <input id="address" name="address" type="text" value="603, 408">
Координата X наверно одинаковая, нет? Y-то как раз изменяется на острый конец. Пока так поправил - дай знать, если я что-то не так понял

2020-10-06 22:38 UTC, khisma17 commented on js/main.js
> +const MAIN_PIN_INACTIVE_X = 570 + 65 / 2;
Вычисления добавил, только рассчитывал не от ширины/высоты карты, а от координат left/top, заданных инлайново, потому что они немного отличаются от середины карты

2020-10-08 14:57 UTC, merged