16. Личный проект: надо подкачаться (часть 1)
htmlacademy-javascript/582985-keksobooking-21 pull request #6
Opened 2020-10-15 22:49 UTC by khisma17

1) Дорабатывает модуляцию
2) Добавляет модуль для загрузки данных с сервера

2020-10-17 10:43 UTC, frontstall requested changes

2020-10-17 10:43 UTC, frontstall commented on js/activation.js
> +  const PIN_WIDTH = mainPin.offsetWidth;
Это не константы, поскольку являются производными от чего-то. А если были бы константы, то объявлять их нужно первым делом, перед всем остальным кодом.

2020-10-17 10:43 UTC, frontstall commented on js/activation.js
> +  const mainPinX = MAIN_PIN_INACTIVE_X;
Зачем?)

2020-10-17 10:43 UTC, frontstall commented on js/activation.js
> +    return {setInactivePageMode, onInactiveMainPinClick, onInactiveMainPinEnterPress, activatePage};
Пробелы между фигурными скобками и содержимым в литералах объектов.

2020-10-17 10:43 UTC, frontstall commented on js/card.js
> +    } return wordForms[2];
последний return с новой строки

2020-10-17 10:43 UTC, frontstall commented on js/card.js
> +  const getProperWordFormRooms = (n, wordForms) => {
что такое n?

2020-10-17 10:43 UTC, frontstall commented on js/card.js
> +    cardElementCapacity.textContent = `${cardData.offer.rooms} ${getProperWordFormRooms(cardData.offer.rooms, wordFormsRooms)} для ${cardData.offer.guests} ${getProperWordFormGuests(cardData.offer.gu
Вложенные вызовы плохо читаются, давай вынесем в промежуточную переменную с хорошим названием.

2020-10-17 10:43 UTC, frontstall commented on js/card.js
> +  window.card = {createCard};
пробелы

2020-10-17 10:43 UTC, frontstall commented on js/load.js
> +  const StatusCode = {
это словарь, давай назовём во множественном числе

2020-10-17 10:43 UTC, frontstall commented on js/load.js
> +        onError(`Статус ответа: ` + xhr.status + `` + xhr.statusText);
интерполяция. Конкатенация не нужна :)

2020-10-17 10:43 UTC, frontstall commented on js/load.js
> +  const handleError = (errorMessage) => {
Кажется, этой функции тут не место

2020-10-17 13:56 UTC, khisma17 commented on js/activation.js
> +    return {setInactivePageMode, onInactiveMainPinClick, onInactiveMainPinEnterPress, activatePage};
Линтер их убирает, я пробовал)

2020-10-19 09:46 UTC, frontstall commented on js/activation.js
> +  const initiatePageActivation = (url, onSuccess, onError) => {
Смотри, как можно вынести все вызовы querySelector в main.js:

```
const initiatePageActivation = (elements, loadData) => { // Кстати, эта функция ничего не инициализирует, она возвращает функции. Можно назвать её что-то вроде getPageActivationHandlers
// elements содержит объект со ссылками на дом-элементы
// Использование функции загрузки напрямую:
  const activatePage = () => {
    loadData();
  };
}; 
```

2020-10-19 09:46 UTC, frontstall commented on js/card.js
> +  const wordFormsRooms = [`комната`, `комнаты`, `комнат`];
В продакшне для работы с текстами используются специальные библиотеки. Эта тема выходит за рамки текущего интенсива, поэтому у нас два выхода:
1) пишем свой микроинструмент для работы с текстами. Ключевая мысль - тексты хранятся в объекте, и доступ к ним осуществляется по ключам, например:

```
const textMapping = {
  rooms: {
    nominative: 'комнаты',
    genitive: 'комнат',
  },
  guests: {

  },
};
```

Доступ к нужному слову выглядит не просто как обращение к неизвестному элементу массива, а хорошо читается:
```
if (roomsCount >= 5) { // тут может быть другое условие. Кстати, в нашем проекте вполне ограниченное количество опций, который пользователь может выбрать, поэтому, кажется, можно не обрабатывать случаи типа "23 комнаты", тут это не будет ошибкой. В настоящем проекте этим вообще никто заниматься не будет вручную.
  return textMapping.rooms.genitive; // 'комнат'
}
```

Для общего развития: если в словарь ввести ключи верхнего уровня с названиями языков, то можно легко реализовать мультиязычность. Примерно так это и работает :)

2) реализовать решение вообще без словарей:
```
const getRoomsCountText = (roomsCount) => {
  if (roomsCount === 1) {
    return `${roomsCount} комната`;
  }
};
```

2020-10-19 09:46 UTC, merged